<?php


namespace common\components;

use yii\base\Widget;


class FilterProdWidget extends Widget
{

    public $url; // роут с категорией товаров

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $category_id = $this->url['1']['id'];

        return $this->render('menu_tpl\filter', compact('category_id'));

    }

}