<?php


namespace backend\components;

use common\models\LoginForm;
use Yii;
use yii\web\Controller;
use yii\web\HttpException;

class AppController extends Controller
{

    public function beforeAction($action)
    {
        $this->view->title = \Yii::$app->name;
        return parent ::beforeAction($action); // TODO: Change the autogenerated stub
    }

    protected function setMeta($title = null, $description= null)
    {
        $this->view->title = $title;
        $this->view->registerMetaTag(['name' => 'description', 'content' => "$description"]);

    }


}